language: node_js
node_js:
  - "11"

jobs:
  include:
    - stage: npm release
      node_js: "11"
      script: yarn install
      deploy:
        provider: npm
        email: "support@snax.one"
        api_key: "$NPM_API_KEY"
        skip_cleanup: true
        on:
          branch: master
